<a href="https://colab.research.google.com/github/Nikolas2ms/Test_Code_/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [5]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  \
0                       k12inc-my.sharepoint.com        0        0   
1                       aurorabusinessunited.org        0        0   
2                           novinroyapolymer.com        0        0   
3  paypal.co.uk.useriazi6bqgssb.settingsppup.com        0        0   
4                                     medium.com        0        0   

   URL_Length  URL_Depth  Redirection  https_Domain  TinyURL  Prefix/Suffix  \
0           1          5            0             0        1              1   
1           0          2            0             0        0              0   
2           0          0            0             0        0              0   
3           0          0            0             0        0              0   
4           1          2            0             0        0              0   

   DNS_Record  Web_Traffic  Domain_Age  Domain_End  iFrame  Mouse_Over  \
0           0            0           1           1       0           0   
1           0            1           0           1       1           1   
2           0            0           0           1       0           0   
3           0            1           0           1       0           0   
4           0            1           0           1       0           0   

   Right_Click  Web_Forwards  Label  
0            1             0      1  
1            1             1      1  
2            1             0      1  
3            1             0      1  
4            1             0      0

In [6]:
X = data.drop(['Domain', 'Label'], axis=1)

In [7]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          5            0             0   
1        0        0           0          2            0             0   
2        0        0           0          0            0             0   
3        0        0           0          0            0             0   
4        0        0           1          2            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        1              1           0            0           1           1   
1        0              0           0            1           0           1   
2        0              0           0            0           0           1   
3        0              0           0            1           0           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       1           1            1             1  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [9]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [11]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [13]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8063333333333333
Precision: 0.8295198045764575
Recall: 0.8063333333333333
F1 Score: 0.8029533345410467
Confusion Matrix:
[[1404   92]
 [ 489 1015]]

SVC Metrics:
Accuracy: 0.836
Precision: 0.866170537059275
Recall: 0.836
F1 Score: 0.8326266466377599
Confusion Matrix:
[[1465   31]
 [ 461 1043]]

RandomForestClassifier Metrics:
Accuracy: 0.862
Precision: 0.8687317617726827
Recall: 0.862
F1 Score: 0.8613965940236304
Confusion Matrix:
[[1390  106]
 [ 308 1196]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8546666666666667
Precision: 0.8695088038633904
Recall: 0.8546666666666667
F1 Score: 0.8532385593172173
Confusion Matrix:
[[1428   68]
 [ 368 1136]]

KNeighborsClassifier Metrics:
Accuracy: 0.8246666666666667
Precision: 0.8246666666666667
Recall: 0.8246666666666667
F1 Score: 0.8246666666666667
Confusion Matrix:
[[1233  263]
 [ 263 1241]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8596666666666667
Precision: 0.8702534726935434
Recall: 0.8596666666666667
F1 Score: 0.8586936704707414
Confusion Matrix:
[[1412   84]
 [ 337 1167]]


In [14]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.862000   0.868732  0.862000  0.861397
5  DecisionTreeClassifier  0.859667   0.870253  0.859667  0.858694
3           MLPClassifier  0.854667   0.869509  0.854667  0.853239
1                     SVC  0.836000   0.866171  0.836000  0.832627
4    KNeighborsClassifier  0.824667   0.824667  0.824667  0.824667
0      LogisticRegression  0.806333   0.829520  0.806333  0.802953
